defaults:
  - _self_  # defaults lists override entries from this file!
  # data
  - sampling: default__bb
  - dataset: xyobject
  - augment: example
  # system
  - framework: betavae
  - model: linear
  # training
  - optimizer: adam
  - schedule: beta_cyclic
  - metrics: test
  - run_length: test
  # logs
  - run_callbacks: test
  - run_logging: none
  # runtime
  - run_location: local_cpu
  - run_launcher: local
  - run_action: train
  # experiment
  - run_plugins: default

settings:
  job:
    user: 'invalid'
    project: 'invalid'
    name: '${framework.name}:${settings.framework.recon_loss}|${dataset.name}:${sampling.name}|${trainer.max_steps}'
    seed: NULL
  framework:
    beta: 0.0316
    recon_loss: mse
    loss_reduction: mean  # beta scaling
  framework_opt:
    latent_distribution: normal  # only used by VAEs
    overlap_loss: NULL           # only used for experimental dotvae and dorvae
    usage_ratio: 0.5             # only used by adversarial masked datasets
  model:
    z_size: 25
    weight_init: 'xavier_normal'  # xavier_normal, default
  dataset:
    batch_size: 5
  optimizer:
    lr: 1e-3
